const ALL_ORDERS_WS_CONNECTION_START = 'ALL_ORDERS_WS_CONNECTION_START';
const ALL_ORDERS_WS_CONNECTION_SUCCESS = 'ALL_ORDERS_WS_CONNECTION_SUCCESS';
const ALL_ORDERS_WS_CONNECTION_ERROR = 'ALL_ORDERS_WS_CONNECTION_ERROR';
const ALL_ORDERS_WS_CONNECTION_CLOSED = 'ALL_ORDERS_WS_CONNECTION_CLOSED';
const ALL_ORDERS_WS_GET_MESSAGE = 'ALL_ORDERS_WS_GET_MESSAGE';
const ALL_ORDERS_WS_SEND_MESSAGE = 'ALL_ORDERS_WS_SEND_MESSAGE';
const ALL_ORDERS_WS_CLOSE_CONNECTION = 'ALL_ORDERS_WS_CLOSE_CONNECTION';

export {
  ALL_ORDERS_WS_CONNECTION_START,
  ALL_ORDERS_WS_CONNECTION_SUCCESS,
  ALL_ORDERS_WS_CONNECTION_ERROR,
  ALL_ORDERS_WS_CONNECTION_CLOSED,
  ALL_ORDERS_WS_GET_MESSAGE,
  ALL_ORDERS_WS_SEND_MESSAGE,
  ALL_ORDERS_WS_CLOSE_CONNECTION
}