const USER_ORDERS_WS_CONNECTION_START = 'USER_ORDERS_WS_CONNECTION_START';
const USER_ORDERS_WS_CONNECTION_SUCCESS = 'USER_ORDERS_WS_CONNECTION_SUCCESS';
const USER_ORDERS_WS_CONNECTION_ERROR = 'USER_ORDERS_WS_CONNECTION_ERROR';
const USER_ORDERS_WS_CONNECTION_CLOSED = 'USER_ORDERS_WS_CONNECTION_CLOSED';
const USER_ORDERS_WS_GET_MESSAGE = 'USER_ORDERS_WS_GET_MESSAGE';
const USER_ORDERS_WS_SEND_MESSAGE = 'USER_ORDERS_WS_SEND_MESSAGE';
const USER_ORDERS_WS_CLOSE_CONNECTION = 'USER_ORDERS_WS_CLOSE_CONNECTION';

export {
  USER_ORDERS_WS_CONNECTION_START,
  USER_ORDERS_WS_CONNECTION_SUCCESS,
  USER_ORDERS_WS_CONNECTION_ERROR,
  USER_ORDERS_WS_CONNECTION_CLOSED,
  USER_ORDERS_WS_GET_MESSAGE,
  USER_ORDERS_WS_SEND_MESSAGE,
  USER_ORDERS_WS_CLOSE_CONNECTION
}